name:                coderpad
version:             0.1.0.0
github:              "dbaynard/coderpad"
license:             Apache-2.0 OR BSD-3-Clause
author:              "David Baynard"
maintainer:          "haskell@baynard.dev"
copyright:           "David Baynard 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            test

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbaynard/coderpad#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  coderpad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coderpad

tests:
  coderpad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coderpad
